export const AllRoutes = {
  HomeStacks: 'HomeStacks',
  AUTH: 'AuthStacks',
  LOGIN: 'Login',
  HOMESCREEN: 'HomeScreen',
  OnboardingScreen: 'OnboardingScreen',
  PinNumber: 'PinNumber',
  Register: 'Register',
  TabStacks: 'TabStacks',
  HelpStacks: 'HelpStacks',
  HelpScreen: 'HelpScreen',
  PactsStacks: 'PactsStacks',
  PactsScreen: 'PactsScreen',
  ProfileStacks: 'ProfileStacks',
  ProfileScreen: 'ProfileScreen',
  TrackStacks: 'TrackStacks',
  TrackScreen: 'TrackScreen',
  CreatePactScreen: 'CreatePactScreen',
  Account: 'Account',
  Feedback: 'Feedback',
};
